name: Prevent Python files in repo root

on:
  push:
    branches:
      - main
      - master
      - "**" # Catch all branches
    paths:
      - "*.py" # Only trigger if root-level .py files are pushed
  pull_request:
    branches:
      - main
      - master
      - "**"
    paths:
      - "*.py"

jobs:
  check-root-py-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Look for .py files in the root directory
        run: |
          ROOT_PY_FILES=$(find . -maxdepth 1 -type f -name "*.py")

          if [ -n "$ROOT_PY_FILES" ]; then
            echo "❌ ERROR: Python files found in the root of the repository:"
            echo "$ROOT_PY_FILES"
            echo "Please move them to an appropriate folder like a run directory."
            exit 1
          else
            echo "✅ No root-level Python files detected. You're good to go!"
          fi
